base_url: "https://crowdin.com"
project_id_env: 477189
api_token_env: 8b7a9ac903ecbc6ee42889d0b69b5546
preserve_hierarchy: true

files:
  - source: /resources/locale/default.pot
    translation: /resources/locale/%locale_with_underscore%.UTF-8/LC_MESSAGES/default.po

  - source: /resources/locale/frontend.pot
    translation: /resources/locale/%locale_with_underscore%.UTF-8/LC_MESSAGES/frontend.po
