version : '2.2'

services :
  installer :
    container_name : playcast_installer
    image : 'ghcr.io/playcast/web:${PLAYCAST_VERSION:-latest}'
    volumes :
      - './:/installer'
    restart : 'no'
    user : root
    entrypoint : docker_installer
    command : install
