---
  - name: Generate PlayCast Password
    command: pwgen 8 -sn 1
    register: prod_playcast_user_password

  - name: Create Groups
    group: name="{{ item }}" state=present
    with_items:
     - www-data
     - admin

  - name: Create PlayCast User
    user:
      name: playcast
      home: "{{ app_base }}"
      comment: "PlayCast"
      shell: /bin/bash
      groups: 'sudo,admin,www-data'
      password: "{{ prod_playcast_user_password.stdout|password_hash('sha512') }}"
    notify: send user notification

  - name: Modify www-data User
    user: name=www-data groups="playcast" append=yes
